(() => {
  const assert = (value, message) => { if (!value) throw new Error(message); };
  resetScenePresentation();
  gameState = StoryEngine.createState();
  gameState.protagonistName = "Álex <viajero>";
  StoryEngine.start(gameState, STORY_SCENES, "vestibulo");
  coverScreen.hidden = true; gameScreen.hidden = false; renderScene();
  pauseToCover.click();
  assert(isGamePaused && gameScreen.inert && !pauseMenu.hidden && coverScreen.hidden, "Menú no pausa");
  assert(document.getElementById("pause-heading").textContent === gameState.protagonistName, "Nombre inseguro");
  advanceDialogue();
  gameScreen.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", bubbles: true }));
  assert(gameState.node === "c2_001", "Avanza durante pausa");
  showCompanions();
  assert(pauseContent.textContent.includes("Lyra") && !pauseContent.textContent.includes("Iven"), "Compañero no encontrado visible");
  showCompanion("lyra");
  assert(pauseContent.querySelector(".affinity-level").textContent === "1", "Falta nivel inicial");
  assert(pauseContent.querySelector(".companion-portrait").style.objectPosition === "center top", "Encuadre de Lyra incorrecto");
  gameState.affinity.lyra = 0; showCompanion("lyra");
  assert(pauseContent.querySelector(".affinity-level").textContent === "0", "El corazón debe mostrar cero");
  assert(StoryEngine.restore(gameState, STORY_SCENES).affinity.lyra === 0, "La carga debe conservar cero");
  gameState.affinity.lyra = 3; showCompanion("lyra");
  assert(pauseContent.querySelector(".affinity-level").textContent === "3", "No refleja aumento de afinidad");
  const legacy = JSON.parse(JSON.stringify(gameState));
  legacy.affinity.lyra = "Por conocer";
  assert(StoryEngine.restore(legacy, STORY_SCENES).affinity.lyra === 1, "No migra afinidad antigua");
  assert(StoryEngine.restore(gameState, STORY_SCENES).affinity.lyra === 3, "No conserva nivel guardado");
  showHistory();
  assert(!pauseContent.querySelector('.history-entry'), "Listado muestra todo el texto");
  assert(pauseContent.querySelectorAll('.history-chapter').length === 1, "Capítulos no visitados visibles");
  pauseContent.querySelector('.history-chapter').click();
  assert(pauseContent.textContent.includes(STORY_SCENES.vestibulo.nodes.c2_001.text), "Falta historia leída");
  assert(!pauseContent.textContent.includes(STORY_SCENES.vestibulo.nodes.c2_002.text), "Historia adelanta texto");
  closePauseMenu();
  assert(!isGamePaused && !gameScreen.inert && gameState.node === "c2_001", "No reanuda en mismo bloque");
  gameState.node = "c2_040"; renderScene();
  assert(!gameState.metCompanions.includes("iven"), "Iven no es un compañero");
  const saved = JSON.parse(JSON.stringify(gameState));
  saved.metCompanions.push("iven"); saved.affinity.iven = 1;
  gameState = StoryEngine.restore(saved, STORY_SCENES);
  assert(!gameState.metCompanions.includes("iven") && gameState.metCompanions.includes("lyra"), "No corrige compañeros guardados");
  assert(!("iven" in gameState.affinity) && gameState.affinity.lyra === 3, "Migración altera afinidad de compañeros");
  openPauseMenu(); showCompanions();
  assert(!pauseContent.textContent.includes("Iven"), "Iven aparece en compañeros");
  showCompanion("iven");
  assert(!pauseContent.querySelector(".companion-portrait"), "Permite abrir ficha de Iven");
  closePauseMenu();
  gameState.node = "c2_e1"; renderScene();
  openPauseMenu(); const count = gameState.decisions.length;
  choicesPanel.firstElementChild.click();
  assert(gameState.decisions.length === count, "Elección activa durante pausa");
  closePauseMenu(); choicesPanel.firstElementChild.click();
  assert(gameState.decisions.length === count + 1, "Elección no se reanuda");
  const progress = JSON.parse(JSON.stringify(gameState));
  StoryEngine.start(gameState, STORY_SCENES, 'c3_inspeccion');
  gameState.node = 'descanso_decision_01'; StoryEngine.prepare(gameState, STORY_SCENES);
  gameState = StoryEngine.restore(gameState, STORY_SCENES);
  showHistory();
  assert(pauseContent.querySelectorAll('.history-chapter').length === 3, 'Capítulos y descanso no separados al cargar');
  assert(!pauseContent.querySelector('.history-entry'), 'Texto acumulado en listado');
  const before = JSON.stringify(gameState);
  showHistoryChapter('descanso');
  assert(pauseContent.textContent.includes('Necesito descansar un rato.'), 'Falta descanso');
  assert(!pauseContent.textContent.includes('El edificio de Inspección'), 'Mezcla capítulos');
  pauseContent.querySelector('.menu-back').click();
  assert(pauseContent.querySelectorAll('.history-chapter').length === 3, 'Flecha no vuelve a capítulos');
  assert(JSON.stringify(gameState) === before, 'Leer historial cambia progreso');
  assert(!document.getElementById('advance-dialogue').textContent.includes('Continuar'), 'Continúa mostrando la etiqueta');
  gameState = StoryEngine.restore(progress, STORY_SCENES);
  return "OK pausa: capítulos desplegados por separado, descanso, carga, lectura sin alterar progreso, bloqueo, compañeros y afinidad.";
})()
